// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkBqBlamPVxbRNM3T3u4BKiZOUiwgpQfY',
    appId: '1:484573932621:web:9ef030ac1876e86c9a0004',
    messagingSenderId: '484573932621',
    projectId: 'as-lojeans',
    authDomain: 'as-lojeans.firebaseapp.com',
    storageBucket: 'as-lojeans.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaVrrjTEvv7leMarybx_zTcbnjTv8gd58',
    appId: '1:484573932621:android:1691099dd6200ea79a0004',
    messagingSenderId: '484573932621',
    projectId: 'as-lojeans',
    storageBucket: 'as-lojeans.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABcoVZarlQA0ZP8t_AX0wI0Tj6SjD_nxc',
    appId: '1:484573932621:ios:160d998e87f251179a0004',
    messagingSenderId: '484573932621',
    projectId: 'as-lojeans',
    storageBucket: 'as-lojeans.appspot.com',
    iosBundleId: 'com.example.lojeansApp',
  );

}